package CRUD_Java;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

// Importação das classes necessárias para a aplicação
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*  @author André Olímpio  */

public class Tela_Login extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Login
     */
    public Tela_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_Painel = new javax.swing.JPanel();
        Lbl_Login = new javax.swing.JLabel();
        Txt_Login = new javax.swing.JTextField();
        Lbl_Senha = new javax.swing.JLabel();
        Txt_Senha = new javax.swing.JPasswordField();
        Btn_Validar = new javax.swing.JButton();
        Btn_Limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD Java - Tela de Login");
        setResizable(false);

        Pnl_Painel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Lbl_Login.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Lbl_Login.setText("Login:");
        Lbl_Login.setName("Lbl_Login"); // NOI18N

        Txt_Login.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        Lbl_Senha.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Lbl_Senha.setText("Senha:");

        Btn_Validar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Btn_Validar.setText("Validar");
        Btn_Validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ValidarActionPerformed(evt);
            }
        });

        Btn_Limpar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Btn_Limpar.setText("Limpar");
        Btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_PainelLayout = new javax.swing.GroupLayout(Pnl_Painel);
        Pnl_Painel.setLayout(Pnl_PainelLayout);
        Pnl_PainelLayout.setHorizontalGroup(
            Pnl_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_PainelLayout.createSequentialGroup()
                .addGroup(Pnl_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_PainelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(Pnl_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Senha)
                            .addComponent(Lbl_Login))
                        .addGap(18, 18, 18)
                        .addGroup(Pnl_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txt_Login)
                            .addComponent(Txt_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Pnl_PainelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Btn_Validar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        Pnl_PainelLayout.setVerticalGroup(
            Pnl_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_PainelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(Pnl_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lbl_Login)
                    .addComponent(Txt_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pnl_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_Senha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(Pnl_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Validar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pnl_Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(Pnl_Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ValidarActionPerformed
        // Declaração de variáveis locais
        String usuario = Txt_Login.getText();
        String senha = Txt_Senha.getText();
        String sql = "Select login, senha, status, nome, tipo from usuarios where login = ?";

        // Instanciando a variável conexao
        Conexao_BD conexao;

        // Estrutura para conexão com banco de dados
        try {
            conexao = new Conexao_BD();
            PreparedStatement valida_senha = conexao.getConexao().prepareStatement(sql);
            valida_senha.setString(1, usuario);
            ResultSet resultado = valida_senha.executeQuery();
            
            // Armazenamento do retorno da instrução SELECT em um vetor
            while (resultado.next()) {
                String[] retorno = new String[5];
                retorno[0] = resultado.getString("login");
                retorno[1] = resultado.getString("senha");
                retorno[2] = resultado.getString("nome");
                retorno[3] = resultado.getString("status");
                retorno[4] = resultado.getString("tipo");
        
                // Efetuando a validação de usuário / senha
                if ((!usuario.equals(retorno[0])) || (!senha.equals(retorno[1]))) {
                    JOptionPane.showMessageDialog(this,"Usuário e/ou senha inválidos!!! Por favor, digite novamente!!!");
                }
                else {
                    if (retorno[3].equals("B")){
                        JOptionPane.showMessageDialog(this,"Usuário Bloqueado!!! Favor, entrar em contato com o administrador!!!");
                    }
                    else{
                        dispose();
                        new Tela_Principal().setVisible(true);
                    }
                }
            }
        }

        // Tratamento da exceção para erro de conexão com o banco de dados
        catch(Exception excecao) {
            JOptionPane.showMessageDialog(this,excecao.getMessage(),"ERRO",JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_Btn_ValidarActionPerformed

    private void Btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimparActionPerformed
        Txt_Login.setText("");
        Txt_Senha.setText("");
        Txt_Login.requestFocus(true);
    }//GEN-LAST:event_Btn_LimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Limpar;
    private javax.swing.JButton Btn_Validar;
    private javax.swing.JLabel Lbl_Login;
    private javax.swing.JLabel Lbl_Senha;
    private javax.swing.JPanel Pnl_Painel;
    private javax.swing.JTextField Txt_Login;
    private javax.swing.JPasswordField Txt_Senha;
    // End of variables declaration//GEN-END:variables

}
